version: '3.8'

services:
  app:
    container_name: portfolio
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3001:3001'
    command: sh -c "chown -R node:node /app && npm install && npm run dev"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
